---
- name: Deploy React App
  hosts: [apps]
  user: vagrant
  become: yes

  tasks:
    - name: Add app User
      user:
        name: app
        comment: Usuário de aplicação
        uid: 500
     
    - name: Download AzCopy package
      get_url:
        url: https://aka.ms/downloadazcopy-v10-linux
        dest: /tmp/downloadazcopy-v10-linux
 
    - name: Unpack AzCopy package
      command: tar -xf /tmp/downloadazcopy-v10-linux

    - name: Move AzCopy executable to /usr/local/bin
      command: mv azcopy_linux_amd64_10.17.0/azcopy /usr/local/bin/
      become: yes

    - name: AzCopy permissions fix
      shell:
        cmd: chmod +x azcopy
        chdir: /usr/local/bin
      become: yes

    - name: Chown AzCopy to user vagrant
      command: chown vagrant:vagrant /usr/local/bin/azcopy
      become: yes

    - name: npm Install package
      yum:
        name:
          - https://rpm.nodesource.com/pub_14.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
        state: present

    - name: Install Node.js 14.8
      yum:
        name: nodejs-14.8.0-1nodesource
        state: present

    - name: NPM Prepare and Install 
      shell: npm install
      become: yes

    - name: Creation of app directory
      file:
        path: /opt/calc
        state: directory
        owner: app
        group: app
 
    - name: Git Client Instalation
      yum:
        name: git
        state: latest
  
    - name: Repo Clone Calculator - app
      git:
        repo: 'https://github.com/ahfarmer/calculator.git'
        dest: /opt/calc
        clone: yes
        force: yes

    - name: NPM Clean Cache
      shell: npm cache clean --force
      become: yes

    - name: NPM Install 
      shell: npm install
      become: yes

    - name: NPM Install React-Scripts
      shell: npm install react-scripts
      become: yes

    - name: NPM Audit Fix
      shell:
        cmd: npm audit fix
        chdir: /opt/calc/
      become: yes

    - name: Application Package Build
      shell:
        cmd: npm run build
        chdir: /opt/calc/
      become: yes

    - name: Create "calculator" folder (Fix React under blob storage)
      shell: mkdir -p "/opt/calc/build/calculator"
      become: yes

    - name: Copy build files to "calculator" folder (Fix React under blob storage)
      shell: cp -R "/opt/calc/build/" "/tmp/calculator/" && sudo cp -R "/tmp/calculator/" "/opt/calc/build/" && sudo rm -f -r /opt/calc/build/calculator/build
      become: yes

    - name: copy (build/calculator) to storage
      shell: /usr/local/bin/azcopy copy "/opt/calc/build/calculator/" "https://coodeshdevops.blob.core.windows.net/%24web/?sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2023-01-30T04:50:59Z&st=2023-01-24T20:50:59Z&spr=https&sig=6yhlm150I7n5N%2BnYzXf4FTGurRBZeq3Ptet0yBssdRg%3D" --recursive=true --overwrite=true && /usr/local/bin/azcopy copy "/opt/calc/build/*.*" "https://coodeshdevops.blob.core.windows.net/%24web/?sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2023-01-30T04:50:59Z&st=2023-01-24T20:50:59Z&spr=https&sig=6yhlm150I7n5N%2BnYzXf4FTGurRBZeq3Ptet0yBssdRg%3D" --recursive=true --overwrite=true
      become: yes      

    - name: The application is available on https://coodeshdevops.z13.web.core.windows.net/ 
      shell: echo "The application is available on https://coodeshdevops.z13.web.core.windows.net/"