Vagrant.configure('2') do |config| 
  config.vm.define "slave" do |slave|
    slave.vm.box = 'azure'
    slave.ssh.private_key_path = "~/.ssh/id_rsa" # CAUTION - pub and private keys (Clean up after deploying)
    config.ssh.insert_key = "~/.ssh/id_rsa"
    config.ssh.forward_agent = true
    slave.vm.provider :azure do |azure2, override2|
      #Enter the azure information bellow (turn into variables) - If you got an error to deploy the VM, set the Service Principal using azure cli --role --scopes
      azure2.tenant_id = "XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX"
      azure2.client_id = "XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX"
      azure2.client_secret = "XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX"
      azure2.subscription_id = "XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX"
      #Specify VM parameters
      azure2.vm_name = 'app01-coodesh'
      azure2.resource_group_name ='coodesh-test'
      azure2.location = 'eastus'
      azure2.vm_image_urn = 'OpenLogic:CentOS:7.5:latest'
      azure2.instance_ready_timeout = 600
      azure2.vm_password = 'vagrant'
      azure2.admin_username = "vagrant"
      override2.winrm.transport = :ssl
      override2.winrm.port = 5986
      override2.winrm.ssl_peer_verification = false # must be false if using a self signed cert
      azure2.tcp_endpoints = "3000"
    end
    slave.vm.synced_folder ".", "/vagrant", type: "rsync" 
    slave.vm.network "private_network", ip: "10.0.0.4"
    port_forward_network_pause = true 
    slave.vm.network "forwarded_port", guest: 3000, host: 3000
    virtual_network_name='coodesh-1980'
    slave.vm.provision "shell", path: "provision2.sh"
  end
  
  config.vm.define "control", primary: true do |control|
    control.vm.provision "shell", inline: "sleep 10"
    control.vm.box = 'azure'
    control.ssh.private_key_path = "~/.ssh/id_rsa" # CAUTION - pub and private keys (Clean up before deploying)
  config.ssh.insert_key = "~/.ssh/id_rsa"
  config.ssh.forward_agent = true
    control.vm.synced_folder ".", "/vagrant", type: "rsync"
    control.vm.provision "shell", path: "provision.sh"
    control.vm.provider :azure do |azure, override|
    control.vm.network "private_network", ip: "10.0.0.5"
    virtual_network_name='coodesh-1980'
    # enter the azure information bellow - If you got an error to deploy the VM, set the Service Principal using azure cli --role contributor --scopes
    azure.tenant_id = "XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX"
    azure.client_id = "XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX"
    azure.client_secret = "XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX"
    azure.subscription_id = "XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX"
    #Specify VM parameters
    azure.vm_name = 'control-node'
    azure.resource_group_name ='coodesh-test'
    azure.location = 'eastus'
    azure.vm_image_urn = 'OpenLogic:CentOS:7.5:latest'
    azure.instance_ready_timeout = 600
    azure.vm_password = 'vagrant'
    azure.admin_username = "vagrant"
    override.winrm.transport = :ssl
    override.winrm.port = 5986
    override.winrm.ssl_peer_verification = false # must be false if using a self signed cert
    end
  end
end


